parameters:

services:
    # _default is never inherited, it applies only to the current file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # _instanceof is never inherited, it applies only to the current file

    App\Entity\Address\:
        resource: '../../*'
        exclude: ['../Tests']
