parameters:

services:
    # _default is never inherited, it applies only to the current file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

    App\Doctrine\:
        resource: '../../*'

# > Cache --------------------------------------------------------------------------------------------------------------
    app_doctrine_cache:
        class: App\Cache\SimpleCacheBridge
        arguments:
            - '@memcached'
            - 'app_doctrine'
# < Cache --------------------------------------------------------------------------------------------------------------
